/**
 * Supabase Database Types
 *
 * This file should be auto-generated by Supabase CLI.
 * Run: supabase gen types typescript --local > packages/shared/src/types/database.ts
 *
 * For now, we have manually created types to match the migration schema.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Define enums as standalone types first to avoid circular references
export type UserRole = 'admin' | 'manager' | 'instructor' | 'student';
export type DocumentStatus = 'missing' | 'pending' | 'approved' | 'rejected';
export type ProductType = 'permit' | 'reactivation' | 'post_permit';
export type OrderStatus = 'pending' | 'paid' | 'failed' | 'refunded';
export type SessionType = 'theory' | 'practice';
export type EnrollmentStatus = 'assigned' | 'cancelled' | 'noshow' | 'completed';
export type PenaltyType = 'noshow' | 'late_cancel';
export type NotificationType = 'message' | 'system';

export type Database = {
  public: {
    Tables: {
      sites: {
        Row: {
          id: string;
          name: string;
          city: string | null;
          region: string | null;
          timezone: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          city?: string | null;
          region?: string | null;
          timezone?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          city?: string | null;
          region?: string | null;
          timezone?: string;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          user_id: string;
          role: UserRole;
          full_name: string | null;
          phone: string | null;
          primary_site_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          role?: UserRole;
          full_name?: string | null;
          phone?: string | null;
          primary_site_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          role?: UserRole;
          full_name?: string | null;
          phone?: string | null;
          primary_site_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'profiles_primary_site_id_fkey';
            columns: ['primary_site_id'];
            isOneToOne: false;
            referencedRelation: 'sites';
            referencedColumns: ['id'];
          },
        ];
      };
      profile_sites: {
        Row: {
          user_id: string;
          site_id: string;
        };
        Insert: {
          user_id: string;
          site_id: string;
        };
        Update: {
          user_id?: string;
          site_id?: string;
        };
        Relationships: [];
      };
      students: {
        Row: {
          user_id: string;
          site_id: string;
          oedipp_number: string | null;
          oedipp_set_at: string | null;
          consent_marketing: boolean;
          created_at: string;
        };
        Insert: {
          user_id: string;
          site_id: string;
          oedipp_number?: string | null;
          oedipp_set_at?: string | null;
          consent_marketing?: boolean;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          site_id?: string;
          oedipp_number?: string | null;
          oedipp_set_at?: string | null;
          consent_marketing?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      document_types: {
        Row: {
          id: string;
          key: string;
          label: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
          description?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      site_required_documents: {
        Row: {
          site_id: string;
          document_type_id: string;
          is_required: boolean;
        };
        Insert: {
          site_id: string;
          document_type_id: string;
          is_required?: boolean;
        };
        Update: {
          site_id?: string;
          document_type_id?: string;
          is_required?: boolean;
        };
        Relationships: [];
      };
      student_documents: {
        Row: {
          id: string;
          site_id: string;
          student_user_id: string;
          document_type_id: string;
          storage_path: string;
          status: DocumentStatus;
          rejected_reason: string | null;
          uploaded_at: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          student_user_id: string;
          document_type_id: string;
          storage_path: string;
          status?: DocumentStatus;
          rejected_reason?: string | null;
          uploaded_at?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          student_user_id?: string;
          document_type_id?: string;
          storage_path?: string;
          status?: DocumentStatus;
          rejected_reason?: string | null;
          uploaded_at?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
        };
        Relationships: [];
      };
      products: {
        Row: {
          id: string;
          site_id: string;
          type: ProductType;
          name: string;
          description: string | null;
          price_cents: number;
          currency: string;
          access_duration_days: number | null;
          stripe_price_id: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          type: ProductType;
          name: string;
          description?: string | null;
          price_cents: number;
          currency?: string;
          access_duration_days?: number | null;
          stripe_price_id?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          site_id?: string;
          type?: ProductType;
          name?: string;
          description?: string | null;
          price_cents?: number;
          currency?: string;
          access_duration_days?: number | null;
          stripe_price_id?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          site_id: string;
          user_id: string;
          product_id: string;
          status: OrderStatus;
          stripe_checkout_session_id: string | null;
          stripe_payment_intent_id: string | null;
          amount_cents: number;
          currency: string;
          created_at: string;
          paid_at: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          user_id: string;
          product_id: string;
          status?: OrderStatus;
          stripe_checkout_session_id?: string | null;
          stripe_payment_intent_id?: string | null;
          amount_cents: number;
          currency: string;
          created_at?: string;
          paid_at?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          user_id?: string;
          product_id?: string;
          status?: OrderStatus;
          stripe_checkout_session_id?: string | null;
          stripe_payment_intent_id?: string | null;
          amount_cents?: number;
          currency?: string;
          created_at?: string;
          paid_at?: string | null;
        };
        Relationships: [];
      };
      entitlements: {
        Row: {
          id: string;
          site_id: string;
          user_id: string;
          product_id: string | null;
          starts_at: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          user_id: string;
          product_id?: string | null;
          starts_at?: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          site_id?: string;
          user_id?: string;
          product_id?: string | null;
          starts_at?: string;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      sessions: {
        Row: {
          id: string;
          site_id: string;
          type: SessionType;
          starts_at: string;
          ends_at: string;
          capacity: number;
          location: string | null;
          instructor_user_id: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          type: SessionType;
          starts_at: string;
          ends_at: string;
          capacity?: number;
          location?: string | null;
          instructor_user_id?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          site_id?: string;
          type?: SessionType;
          starts_at?: string;
          ends_at?: string;
          capacity?: number;
          location?: string | null;
          instructor_user_id?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      enrollments: {
        Row: {
          id: string;
          site_id: string;
          session_id: string;
          student_user_id: string;
          status: EnrollmentStatus;
          created_at: string;
          cancelled_at: string | null;
          cancelled_by: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          session_id: string;
          student_user_id: string;
          status?: EnrollmentStatus;
          created_at?: string;
          cancelled_at?: string | null;
          cancelled_by?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          session_id?: string;
          student_user_id?: string;
          status?: EnrollmentStatus;
          created_at?: string;
          cancelled_at?: string | null;
          cancelled_by?: string | null;
        };
        Relationships: [];
      };
      penalties: {
        Row: {
          id: string;
          site_id: string;
          student_user_id: string;
          session_id: string | null;
          type: PenaltyType;
          occurred_at: string;
          notes: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          site_id: string;
          student_user_id: string;
          session_id?: string | null;
          type: PenaltyType;
          occurred_at?: string;
          notes?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          site_id?: string;
          student_user_id?: string;
          session_id?: string | null;
          type?: PenaltyType;
          occurred_at?: string;
          notes?: string | null;
          created_by?: string | null;
        };
        Relationships: [];
      };
      exam_centers: {
        Row: {
          id: string;
          site_id: string | null;
          name: string;
          address: string | null;
          city: string | null;
          postal_code: string | null;
          phone: string | null;
          website: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id?: string | null;
          name: string;
          address?: string | null;
          city?: string | null;
          postal_code?: string | null;
          phone?: string | null;
          website?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          site_id?: string | null;
          name?: string;
          address?: string | null;
          city?: string | null;
          postal_code?: string | null;
          phone?: string | null;
          website?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      external_learning_links: {
        Row: {
          student_user_id: string;
          url: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          student_user_id: string;
          url: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          student_user_id?: string;
          url?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      conversations: {
        Row: {
          id: string;
          site_id: string;
          student_user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          student_user_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          site_id?: string;
          student_user_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          site_id: string;
          conversation_id: string;
          sender_user_id: string;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          site_id: string;
          conversation_id: string;
          sender_user_id: string;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          site_id?: string;
          conversation_id?: string;
          sender_user_id?: string;
          body?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          site_id: string | null;
          type: NotificationType;
          title: string;
          body: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          site_id?: string | null;
          type: NotificationType;
          title: string;
          body?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          site_id?: string | null;
          type?: NotificationType;
          title?: string;
          body?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      device_tokens: {
        Row: {
          id: string;
          user_id: string;
          platform: string;
          expo_push_token: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          platform: string;
          expo_push_token: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          platform?: string;
          expo_push_token?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: number;
          site_id: string | null;
          actor_user_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: number;
          site_id?: string | null;
          actor_user_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: number;
          site_id?: string | null;
          actor_user_id?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      current_user_id: {
        Args: Record<PropertyKey, never>;
        Returns: string;
      };
      current_role: {
        Args: Record<PropertyKey, never>;
        Returns: UserRole;
      };
      has_site_access: {
        Args: { _site_id: string };
        Returns: boolean;
      };
    };
    Enums: {
      user_role: UserRole;
      document_status: DocumentStatus;
      product_type: ProductType;
      order_status: OrderStatus;
      session_type: SessionType;
      enrollment_status: EnrollmentStatus;
      penalty_type: PenaltyType;
      notification_type: NotificationType;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// Helper types
export type Tables<
  PublicTableNameOrOptions extends
    | keyof (Database['public']['Tables'] & Database['public']['Views'])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions['schema']]['Tables'] &
        Database[PublicTableNameOrOptions['schema']]['Views'])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions['schema']]['Tables'] &
      Database[PublicTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (Database['public']['Tables'] &
        Database['public']['Views'])
    ? (Database['public']['Tables'] &
        Database['public']['Views'])[PublicTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof Database['public']['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof Database['public']['Tables']
    ? Database['public']['Tables'][PublicTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof Database['public']['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof Database['public']['Tables']
    ? Database['public']['Tables'][PublicTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof Database['public']['Enums']
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions['schema']]['Enums'][EnumName]
  : PublicEnumNameOrOptions extends keyof Database['public']['Enums']
    ? Database['public']['Enums'][PublicEnumNameOrOptions]
    : never;
