/**
 * Supabase Database Types
 *
 * This file will be auto-generated by Supabase CLI.
 * Run: pnpm db:types
 *
 * For now, we export a placeholder that will be replaced
 * after running the migration.
 */

export interface Database {
  public: {
    Tables: {
      sites: {
        Row: {
          id: string;
          name: string;
          city: string | null;
          region: string | null;
          timezone: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['sites']['Row'], 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['sites']['Insert']>;
      };
      profiles: {
        Row: {
          user_id: string;
          role: 'admin' | 'manager' | 'instructor' | 'student';
          full_name: string | null;
          phone: string | null;
          primary_site_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['profiles']['Row'],
          'created_at' | 'updated_at'
        > & {
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      // ... more tables will be generated
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: 'admin' | 'manager' | 'instructor' | 'student';
      document_status: 'missing' | 'pending' | 'approved' | 'rejected';
      product_type: 'permit' | 'reactivation' | 'post_permit';
      order_status: 'pending' | 'paid' | 'failed' | 'refunded';
      session_type: 'theory' | 'practice';
      enrollment_status: 'assigned' | 'cancelled' | 'noshow' | 'completed';
      penalty_type: 'noshow' | 'late_cancel';
      notification_type: 'message' | 'system';
    };
  };
}
