// Export all types
export * from './user';
export * from './document';
export * from './session';
export * from './product';
export * from './message';

// Database types will be auto-generated by Supabase
// Run: pnpm db:types
export type {
  Database,
  Json,
  Tables,
  TablesInsert,
  TablesUpdate,
  Enums,
} from './database';
